# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90a5bb84adceeeb38232a3256a8b9304d394d49dfd366c1a1194bf31d7a66909239e31e6a5c67daa217987118a590ba00051436b49e0f91ea5fcce4d18230d5f

test:
  secret_key_base: 6921763daa70d8a5e51d8ee325f82c4adb11b3c17765c60becffe8af0fb1fbc8f39e4ff242fbafd0c792d4e54afd184f63290b038ace6df1020bf97fa9f8a506

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
